### ISSUE TITLE
Broken code generation involving `where` and `is _ if ... =>`

### ISSUE THREAD

**Issue by aslilac** [ren-lang/compiler#100] opened 2022-02-24 16:14 UTC
Prior to the most recent update, the following code compiled and ran. It still compiles, but the emitted JS now has incorrect syntax. Note the output of the second `if` statement in `verse`.

```coffee
import pkg "ren/array" as Array exposing { forEach }
import pkg "ren/console" as Console exposing { log }

pub let main = _ => {
    let verses = [verse 3, verse 2, verse 1, verse 0]

    ret verses
        |> forEach log 
}

let verse = n => where n
    is 0 =>
        "No more bottles of beer on the wall, no more bottles of beer. " +
        "Go to the store and buy some more, 99 bottles of beer on the wall."
    is _ if n > 0 =>
        `${bottles n} of beer on the wall, ${bottles n} of beer. ` +
        `Take one down and pass it around, ${bottles (n - 1)} of beer on the wall.`


let bottles = n => where n
    is 0 => "no more bottles"
    is 1 => "1 bottle"
    is _ => `${n} bottles`
```

```js
import * as Array from "./.ren/deps/ren/array.ren.mjs"
import {forEach} from "./.ren/deps/ren/array.ren.mjs"
import * as Console from "./.ren/deps/ren/console.ren.mjs"
import {log} from "./.ren/deps/ren/console.ren.mjs"
import * as Compare from "./.ren/deps/ren/compare.ren.mjs"
import * as Function from "./.ren/deps/ren/function.ren.mjs"
import * as Logic from "./.ren/deps/ren/logic.ren.mjs"
import * as Math from "./.ren/deps/ren/math.ren.mjs"
import * as Maybe from "./.ren/deps/ren/maybe.ren.mjs"
import * as Object from "./.ren/deps/ren/object.ren.mjs"
import * as Promise from "./.ren/deps/ren/promise.ren.mjs"
import * as String from "./.ren/deps/ren/string.ren.mjs"

// main :: *
export function main (_) {
    return (() => {
        const verses = [verse (3), verse (2), verse (1), verse (0)]

        return (forEach (log)) (verses)
    })()
}

// verse :: *
function verse (n) {
    return ((n) => {
        if (n === 0) {
            return "No more bottles of beer on the wall, no more bottles of beer. " + "Go to the store and buy some more, 99 bottles of beer on the wall."
        }
        if ( && n > 0) {
            const _ = n

            return `${bottles (n)} of beer on the wall, ${bottles (n)} of beer. ` + `Take one down and pass it around, ${bottles (n - 1)} of beer on the wall.`
        }

        throw new Error("Incomplete pattern match.")
    })(n)
}

// bottles :: *
function bottles (n) {
    return ((n) => {
        if (n === 0) {
            return "no more bottles"
        }
        if (n === 1) {
            return "1 bottle"
        }
        if () {
            const _ = n

            return `${n} bottles`
        }

        throw new Error("Incomplete pattern match.")
    })(n)
}
```

**Comment by Alpvax** [comment] 2022-02-24 16:37
I believe this was caused by the changes in #92, causing `_` to be recognised as a variable name, not a wildcard.

**Comment by hayleigh-dot-dev** [comment] 2022-03-07 23:00
Closed by https://github.com/ren-lang/compiler/commit/52ca3ecac67a1b2a7bbac712ba0f6d375f219c89.

**Closed by hayleigh-dot-dev** 2022-03-07 23:00 UTC
